### ISSUE TITLE
Save readable version only (and some other issues) 

### ISSUE THREAD

**Issue by Mati20187** [go-shiori/shiori#412] opened 2022-03-27 17:36 UTC
Hi, I'm looking for an option to save only the "reader mode" version of bookmarked pages and not have to update archive to have the reader version.
I'm using the precompiled binary on a Raspberry Pi with SQLite db.
I didn't have a good experience with archiving websites in shiori:

- The **title is the URL** of the page, not the actual title
- **To set the actual title as title, I have to update the archive** of a bookmark, then it gets set to the page title
- **Updating the archive** of a bookmark is (in my experience) **the only way to get the reader view** for a page
- There's **no way to only save the readable version** without the original page.

Steps to reproduce this behavior:

1. Click + to add a new bookmark, paste the link and select "Create archive"
2. The bookmark is created but the title is the bookmark's URL, there's no excerpt and no reader view
3. Hover over the bookmark and click the cloud "update archive", select nothing and click yes
4. Refresh the page
5. Now the title is correct, there's an excerpt and there are both reader view and archive

If anything needs clarification or I'm mistaken and some or all of these issues aren't reproducible, please let me know :)
Thank you in advance!

**Comment by fmartingr** [comment] 2022-03-27 19:01
Hey @Mati20187, thanks a lot for the detailed report, greatly appreciated. This is indeed a bug introduced in #217, the article and bookmark details should be fetched correctly when adding a bookmark. Your details helped me pinpoint the cause, thanks you a lot!

This bug should be fixed with #413 :) 

I'm closing this issue as duplicate of #406.

Again, thanks a lot for the report!

**Closed by fmartingr** 2022-03-27 19:01 UTC
Labels: resolution:duplicate

**Comment by Mati20187** [comment] 2022-03-27 20:45
@fmartingr I'm glad it helped :) Could you please address my first question about the possibility of saving only the reader format without archiving the entire page (to save disk space)? Is there such an option but I missed it? Or should I create a separate issue for that?

**Comment by fmartingr** [comment] 2022-03-27 20:56
> @fmartingr I'm glad it helped :) Could you please address my first question about the possibility of saving only the reader format without archiving the entire page (to save disk space)? Is there such an option but I missed it? Or should I create a separate issue for that?

Sorry I missed that! You should be able to bookmark anything without archiving without ticking the "Create archive" option. The readable version should be created regardless of that setting.
