### ISSUE TITLE
Add s3 as storage option

### ISSUE THREAD

**Issue by koolay** [go-shiori/shiori#810] opened 2023-12-30 12:21 UTC
`s3` is  nops. We can implement it by using `https://github.com/fclairamb/afero-s3`

**Comment by fmartingr** [comment] 2023-12-31 10:10
Hey, thanks for the report! To keep the discussion focused in one place I'm closing this as duplicate of #798 since right now there is no specific task to move forward with other storage options until #805 is done and we have time for it.

**Closed by fmartingr** 2023-12-31 10:10 UTC
