### ISSUE TITLE
Adding a URL doesn't automatically create an archive

### ISSUE THREAD

**Issue by thelazyoxymoron** [go-shiori/shiori#385] opened 2022-02-25 06:42 UTC
I have turned on the "Create archive by default" setting and I see the relevant option ticked as well when I'm adding a new URL. However, it doesn't actually create an archive, I have to manually go and do update archive.

**Comment by Grauwolf** [comment] 2022-02-25 18:41
when using SQLite it seems to work as intended. when configuring a PostgreSQL database, I can confirm that no archive is created, even though "create archive" is enabled.

**Comment by fmartingr** [comment] 2022-02-26 10:41
> I have turned on the "Create archive by default" setting and I see the relevant option ticked as well when I'm adding a new URL. However, it doesn't actually create an archive, I have to manually go and do update archive.

Is this happening to you in postgresql as well?

**Comment by MidnightSnowleopard** [comment] 2022-02-26 18:28
I can confirm I am seeing the same behavior with PostgreSQL.  Haven't test for SQLite but the behavior is present on Shiori 1.5.2 and 1.5.2 in docker.

**Comment by thelazyoxymoron** [comment] 2022-02-27 00:45
> Is this happening to you in postgresql as well?

Sorry, should've mentioned this, I'm using Postgresql, haven't tried with SQLite.

**Comment by fukajun** [comment] 2022-09-29 04:46
Maybe I fixed it. Please review PR #480.

**Comment by fmartingr** [comment] 2023-07-21 10:17
Apparently fixed in #484, please open a new issue if you experience something similar again.

**Closed by fmartingr** 2023-07-21 10:17 UTC
Labels: type:bug, tag:more-info, component:backend, database:postgres, priority:high
