### ISSUE TITLE
Shiori Running Apache Subpath Issue

### ISSUE THREAD

**Issue by rbdevr** [go-shiori/shiori#283] opened 2020-11-30 18:46 UTC
hello all,

I'm trying to run shiori behind apache.

shiori - http://localhost:5000/shiori

shiori serve -p 5000 --webroot /shiori

apache - http://myserver/shiori

`<Location "/shiori">`
`Require all granted`
`ProxyPass http://localhost:5000/shiori`
`ProxyPassReverse http://localhost:5000/shiori`
`</Location>`

I'm getting the following error:

"
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

This problem can sometimes be caused by disabling or refusing to accept cookies.
"

Are you guys working on this issue?

Cheers

**Comment by rbdevr** [comment] 2021-04-10 07:21
can we have this fix on the next release? 

This is really required to be able to make shiori available on the internet.

Cheers

**Comment by fmartingr** [comment] 2022-02-06 15:33
Duplicate of #39

**Closed by fmartingr** 2022-02-06 15:33 UTC
