### ISSUE TITLE
Code section in bookmark incorrectly displayed

### ISSUE THREAD

**Issue by ekianjo** [go-shiori/shiori#227] opened 2020-01-03 07:17 UTC
This happens on this particular page for example:

https://rud.is/b/2019/12/27/short-attention-span-theatre-reproducing-axios-1-big-thing-google-trends-2019-news-in-review-with-ggplot2/

the proper page should look like this:
![image](https://user-images.githubusercontent.com/2460824/71711445-72638500-2e44-11ea-96ff-141c0708373a.png)

and it looks like this in shiori:
![image](https://user-images.githubusercontent.com/2460824/71711458-8c9d6300-2e44-11ea-9008-ada9c0127d19.png)

Any way to fix that? Main problem is that line return is dropped in the shiori version.

**Comment by deanishe** [comment] 2020-08-06 22:50
Works fine for me:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/747913/89590273-c190ee80-d847-11ea-8075-7859c221a27e.png">

Can you add the page again and check whether you're still having the issue?

If so, please make sure you're running the latest version of Shiori, and if you are, tell me which browser and OS you're using.

**Comment by ekianjo** [comment] 2020-08-06 23:49
@deanishe first, so glad to see you took over shiori - I was surprised to see an answer to my issue. Let me have a look again and report if the issue still exists.

**Comment by deanishe** [comment] 2020-08-07 00:19
Don't wait too long: who knows how long my initial enthusiasm will last … ;)

**Comment by fmartingr** [comment] 2022-02-06 16:03
Hey @ekianjo this is working for me as well. I'm closing this as I can't reproduce it, but if is still hapenning on your end please comment out with more information so we can fix it.

![Screenshot 2022-02-06 at 17 02 52](https://user-images.githubusercontent.com/812088/152689593-a2d2d096-5fb6-4852-b459-5c2c6544f5e3.png)

**Closed by fmartingr** 2022-02-06 16:03 UTC
Labels: bug, front-end
