### ISSUE TITLE
Filtering is not working when there are for example accented characters in tags

### ISSUE THREAD

**Issue by webreg12345** [go-shiori/shiori#245] opened 2020-04-29 20:56 UTC
For example I have the following tags: "árvíztűrő, tükörfúrógép".
The result is empty when I try to search for "árvíz".

**Comment by deanishe** [comment] 2020-08-06 22:08
> The result is empty when I try to search for "árvíz".

It would be: "árvíz" isn't one of your tags. What happens when you search for "árvíztűrő" or "tag:árvíztűrő"?

**Comment by fmartingr** [comment] 2022-02-06 16:22
Tag filtering is working as we currently search for exact matches:

![Screenshot 2022-02-06 at 17 20 58](https://user-images.githubusercontent.com/812088/152690467-2dd42224-cacf-440a-b47d-fd39e2f21b29.png)

I'm closing this issue as it works as intended, if you want to request the feature of partial matches, please do so in the [ideas discussion board](https://github.com/go-shiori/shiori/discussions/categories/ideas).

**Closed by fmartingr** 2022-02-06 16:22 UTC
Labels: as-intended, backend
