### ISSUE TITLE
shiori delete -> "too many SQL variables"

### ISSUE THREAD

**Issue by Dapuva76** [go-shiori/shiori#104] opened 2018-07-29 16:38 UTC
I've imported my pocket list, and am trying to get rid of entries with a certain tag. So I've used
` shiori delete $(shiori search -t tag -i)`
but all I get is
```
too many SQL variables
Bookmark(s) have been deleted
```
Which deletes nothing. There are about 2000+ entries with that tag, so maybe that is confusing. Also, if I try to update all bookmarks via "shiori update", I get a bunch of "unable to retrieve" and a bunch of processed entries, but nothing changed. (manually updating works)

**Comment by RadhiFadlillah** [comment] 2018-07-31 13:13
Hi @Dapuva76 thanks for the report.

> ... which deletes nothing. There are about 2000+ entries with that tag

The `delete` command is working by deleting records in database using query like this :

```sql
DELETE * FROM bookmark WHERE id IN (?, ?, ?, ?, ..., ?);
```

Those `?` are binding variable that will be filled with the submitted ids. The problem is, SQLite by default only allow maximum 999 binding variable. That's why it's failed when trying to delete 2000+ ids.

It's should be easy enough to fix, however right now I'm a bit busy. I think I could start working on it around next weekend, so please bear with it for now :sweat_smile:.

> Also, if I try to update all bookmarks via "shiori update", I get a bunch of "unable to retrieve" and a bunch of processed entries, but nothing changed.

I will investigate it further. BTW, how many bookmarks are you trying to update ? Are there more than 2000 as well ?

**Comment by Dapuva76** [comment] 2018-07-31 22:02
> I will investigate it further. BTW, how many bookmarks are you trying to update ? Are there more than 2000 as well ?

Yeah, I think it's about 4k+ bookmarks. Reason being I've used scripts that scan twitter and reddit for keywords, and automatically add them to pocket. No need to hurry, I love shiori as is! Great app.

**Comment by RadhiFadlillah** [comment] 2019-08-27 12:35
Since the ramadhan branch has been merged, this issue should be fixed now. Therefore, I will close this issue. Feel free to reopen it if the issue still exists.

**Closed by RadhiFadlillah** 2019-08-27 12:35 UTC
Labels: fixed-in-branch
