### ISSUE TITLE
Feature Request: User-Rights-Management

### ISSUE THREAD

**Issue by demlak** [go-shiori/shiori#137] opened 2019-06-15 19:02 UTC
Would be nice to allow specific users "only adding" but not editing.
and/or allow only editing of own bookmarks but not from others.

**Comment by RadhiFadlillah** [comment] 2019-08-27 14:56
Hi @demlak 

With `ramadhan` branch merged, now Shiori has a simple user right management. However, it's not exactly as you want.

In your case, there are two point that you want :

1. User can only modify bookmarks that he created himself.
2. User has separate access level for viewing, adding and editing;

For number one, unfortunately I can't do it without rewriting huge part of code. Shiori at first was intended as CLI app, which make it actually designed to be used by only one person per system.

For number two, I wasn't able to separate the level between add and edit. Sure I can do it, but it need a lot of code which IMHO too much for such little thing. Instead, I combine add and edit into one category, i.e. write operation.

Right now, I made Shiori has two level of account: **owner** and **visitor**. As its name implies, owner is the owner who can add, edit or delete (all write operations) while visitor can only read and see. This is the easiest middle ground that I can do for now.

![multi-account-level](https://user-images.githubusercontent.com/6129042/63782357-7c64fc80-c915-11e9-9967-9aaa295753db.png)

With that saidd, I will close this issue for now. Feel free to reopen it if you think it's needed.

**Closed by RadhiFadlillah** 2019-08-27 14:56 UTC
Labels: fixed-in-branch

**Comment by demlak** [comment] 2019-08-27 16:17
Hey.. thx for this start in user-rights-management.
Since this is only a start, i think, the issue should be held open =)
