### ISSUE TITLE
[Feature Request] Add back bookmarklet support

### ISSUE THREAD

**Issue by imjoeyli** [go-shiori/shiori#218] opened 2019-11-25 16:01 UTC
The latest version seems to have removed the bookmarklet entry, I hope to add it back. For the mobile browser, this is the only way to quickly add bookmarks.

**Comment by clach04** [comment] 2020-08-16 16:28
Recommend closing as duplicate of #189

**Comment by fmartingr** [comment] 2022-02-05 23:10
> Recommend closing as duplicate of #189

Closing as #189 covers this as suggested.

**Closed by fmartingr** 2022-02-05 23:10 UTC
